import PlaceholderPage from '../components/PlaceholderPage';

export default function Reports() {
  return (
    <PlaceholderPage
      title="Reports"
      subtitle="Generate and export reports on asset inventory, assignments, and maintenance"
      columns={['Report Name', 'Type', 'Date Range', 'Generated By', 'Created At', 'Actions']}
    />
  );
}
